name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wb
        path: target/*.war
        retention-days: 5
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy to Remote Server
      uses: pierrickdelrieu/scp-action@v0.1.0
      with:
        host: ${{ secrets.HOST }}
        ssh_username: ${{ secrets.USER_NAME }}
        ssh_key: ${{ secrets.SSH_KEY }}
        source_dir: target/*.war
        destination_dir: wd/tmp
        rm: true

