name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Copy war
      run: mkdir staging && cp target/*.war staging
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
        retention-days: 5
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: staging
          remote: home/wb/temp
          host: 185.173.94.106
          username: root
          password: gNHWBKf

