name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Copy war
      run: mkdir wb && cp target/*.war wb
    - name: Copy dockerfile
      run: cp Dockerfile wb
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: wb
        retention-days: 5
    - name: Echo download path
      run: | 
          cd wb
          ls -la
    - name: Copy folder content recursively to remote
      uses: appleboy/scp-action@v0.1.7
      with:
        source: "wb/wb-1.0.0.war,wb/Dockerfile,tokens"
        target: home
        host: 185.173.94.106
        username: root
        password: gNHWBKf

